### ISSUE TITLE
Eastwood breaks when core.async go blocks return sequence literals

### ISSUE THREAD

**Issue by skazhy** [jonase/eastwood#170]
Here's a simple example:

```clojure
(ns test
  (:require [clojure.core.async :refer [go <!]]))

(defn set-literal [chan]
  (go
    #{(<! chan)}))
```

When trying to lint this code, Eastwood fails with a [rather large](https://gist.github.com/skazhy/98192577368a69f6b7e3) stack trace while in the `analyze+eval` phase.

However, when the `set-literal` function is written as follows:

```clojure
(defn set-literal [chan]
  (go
    (set (<! chan))))
```

Everything works fine. It _could_ be related on how core.async's go macro does transformations internally.

**Comment by jafingerhut** [comment]
Out of curiosity (I haven't used core.async, so am unfamiliar with typical use cases), is the case with the set literal something that is technically legal code, but probably not used very commonly?

Does the set-literal case otherwise work correctly when Eastwood is not involved?

From the stack trace, I suspect you may be right that this is related to how core.async internally transforms code.  Perhaps it is a bug in the version of tools.analyzer.jvm used by Eastwood.  Which version of Eastwood are you using here?

**Comment by Bronsa** [comment]
This is a bug in core.async, I fixed it with a commit a while ago (https://github.com/clojure/core.async/commit/f985e51be4e44840f5ca210dc7c6aff4b67c8d38#diff-3b1b66347975b5531dd27ae5a960a502R83) but there's still no release including it

**Comment by Bronsa** [comment]
I should add -- the reason why it works with core.async and doesn't with eastwood is because eastwood uses tools.reader to read code, which adds line/col metadata to set literals, while clojure doesn't.

```(go ^:foo #{(<! chan_})``` should reproduce the error with core.async
