### ISSUE TITLE
Lint only one file

### ISSUE THREAD

**Issue by saulshanabrook** [jonase/eastwood#195]
I have [created an Atom plugin to integrate Eastwood](https://github.com/saulshanabrook/linter-eastwood) linting, but currently it is very slow because I have it run `lein eastwood` after every save. It would be much faster if I could just lint one filename. I know I can limit the linting to specific namespaces, but it isn't that easy to turn a file path into a namespace.

If it would be possible just to pass in a relative path to a file, that is within the `src` or `test` directories, that would be easiest.

**Comment by arrdem** [comment]
Because Eastwood does macroexpansion and has to boot a JVM this doesn't really make sense. It isn't possible to "just" lint one file, Eastwood has to boot a Clojure runtime with dependencies, load the file you care about it and analyze each form in that file. You'd do much better in terms of responsiveness to investigate invoking [lint-ns](https://github.com/jonase/eastwood/blob/master/src/eastwood/lint.clj#L593) via nREPL or some other live REPL connection. This is basically what [squiggly-clojure](https://github.com/clojure-emacs/squiggly-clojure) does for the same reasons.

**Comment by saulshanabrook** [comment]
It seems like a lot of work to create a linter that hooks up to a nREPL, or keeps one running in the background, so I just added a hacky quick fix that uses a regex to find the namespace from the first line in the current file and runs eastwood just against that one namespace.
