### ISSUE TITLE
Errors on alias-namespaced keywords

### ISSUE THREAD

**Issue by brabster** [jonase/eastwood#200]
I'm linting a namespace in my project that requires foo.bar :as ec2. Then I namespace a keyword ::ec2/cidr-block.

The source is https://github.com/brabster/crucible/blob/1100e30549f60ed22093ebd7fc252886d3f3de43/test/crucible/ec2_test.clj

```
Exception thrown by linter :keyword-typos on namespace crucible.encoding.template_test
Got exception with extra ex-data:
    msg='Invalid token: ::ec2/cidr-block'
    (keys dat)=(:type)
ExceptionInfo Invalid token: ::ec2/cidr-block
    clojure.core/ex-info (core.clj:4718)
    clojure.core/ex-info (core.clj:4718)
    eastwood.copieddeps.dep10.clojure.tools.reader.reader-types/reader-error (reader_types.clj:330)
```

clojure.spec makes extensive use of namespaced keywords so I suspect more people will hit this when 1.9 gets released.

**Comment by rmoehn** [comment]
:+1:

Additionally, suppose I `:require [foo.bar :as ec2]`, so that I can make alias-namespaced keywords with `ec2`, but I don't use anything defined in `foo.bar`. Then Eastwood will give me an `unused-namespaces` warning. 

(I don't know whether requiring is the right thing to do when you're only interested in the alias for keywords, though.)

**Comment by jafingerhut** [comment]
For the original report above, I believe the problem is that the code that you were attempting to lint used namespaced maps, which were introduced in Clojure 1.9.  For that, I have recently updated Eastwood to use the latest version of tools.reader, which should accept those correctly.

For the second comment about `:unused-namespaces` warnings, I have also recently enhanced Eastwood so that any namespaces or namespace aliases used in keywords should cause the namespace to be considered used.

If you want to try it out to see if it fixes the issue for you before the next Eastwood release, you can check out these instructions for locally installing an unreleased version of Eastwood from source code: https://github.com/jonase/eastwood#for-eastwood-developers
