### ISSUE TITLE
it would be nice if there was some way to mark a form as ignorabe by a given linter

### ISSUE THREAD

**Issue by hiredman** [jonase/eastwood#21]
I have a number of compojure routes that look like

``` clojure
(defroutes app
  (GET "/foo" [] #'foo)
  (GET "/bar" [] #'bar))
```

over this form the unused-fn-args complains about some macro generated fun arg not being used, and in the long term it would be nice to get eastwood not to complain about that some how, in the short term it would be great to be able to signal eastwood "I've manually looked at this, and it is fine"

one possibility is some kind of marker macro, but those have issues, and mean you need a runtime component.

maybe something like:

``` clojure
^{:eastwood {:ignore #{:unused-fn-args}}
(defroutes app
  (GET "/foo" [] #'foo)
  (GET "/bar" [] #'bar)))
```

**Comment by amalloy** [comment]
Any news on this? eastwood is pretty cool, but without some way to say "yes, I know what I'm doing in this case" it is not very useful, for the reasons @gfredericks mentions.

**Comment by Bronsa** [comment]
I'll be looking at adding metadata annotations to disable per form linters this week, if @jafingerhut doesn't beat me to it.

**Comment by jafingerhut** [comment]
@Bronsa If you get to it that soon, it would take a miracle for me to beat you to it.  Still trying to get my head above water at work, as I have for the last 2 months.  Go for it!

**Comment by Bronsa** [comment]
just an update -- I've been looking at this over the past few days and it's a little more involved than I'd hoped, not sure how long it's going to take me but I'm definitely interested in having a fix for this as soon as possible

**Comment by jafingerhut** [comment]
One way I had been considering implementing this is roughly as follows -- hack up tools.reader so that it also returns a separate data structure with start & end line & column numbers for each sub-form, and which have metadata like ^{:eastwood/lint ...} (where I don't have anything concrete proposed for what that metadata looks like, except that it should allow you to enable or disable any of the existing or future linters by name, as can be done from the command line for entire Eastwood runs).

Calculate and generate warnings as normal, but just before printing them, check their line/column number.  If it lies within a range of start/end line/column numbers that have the warning suppressed, don't print it.  The finding of the warning's line/column number in the data structure returned by the reader should ideally be a 'narrowest scope' search, i.e. find the smallest sub-form that contains the warning's line/column number, then look for the smallest enclosing form that enables or disables the linter, and use that setting.  This would allow one to give metadata for large forms that enable a warning, but on particular sub-forms of that large form, to disable it.

I only have pieces of such an implementation lying around on disk, from several months to a year or so ago now, mainly the part about hacking up tools.reader, but it isn't in any kind of usable shape.

**Comment by ty-i3** [comment]
+1

The ability to suppress a specific lint warning on a specific form would allow us to fully incorporate eastwood in our dev process, including the CI builds.

**Comment by borkdude** [comment]
FYI, clj-kondo now has something similar, but using reader comments instead of metadata as to not pollute the runtime, but the idea is the same:

https://github.com/borkdude/clj-kondo/issues/872#issuecomment-686760114
