### ISSUE TITLE
False positive Namespace is never user with namespaced keywords

### ISSUE THREAD

**Issue by brabster** [jonase/eastwood#211]
The unused-namespaces linter doesn't recognise when a namespace is imported and its alias is used with a namespaced keyword, like so:

```clojure
(ns foo
  (:require [bar.baz :as baz))

(def x {::baz/wibble ""})
```

**Comment by dtenny** [comment]
Just a note that this is a significant problem as more namespace aliased keywords are added to code for clojure.spec declarations.

**Comment by jafingerhut** [comment]
As Eastwood is implemented right now, using tools.reader to read the source code, that library already converts `::baz/wibble` to `:bar.baz/wibble` before the rest of Eastwood starts its analysis.

What if soeone did this?
```Clojure
(ns foo
  (:require [bar.baz :as baz]))

(def x (:bar.baz/wibble ""})
```

Would you want to have no unused-namespace warning, even though the _alias_ `baz` was never mentioned in the namespace's code, i.e. only the full namespace name `bar.baz` was ever used in keywords?  That I believe I see a way to implement without huge changes in Eastwood.

**Comment by dtenny** [comment]
In this case the namespace might reasonably be said to be used even if not by the alias, and even though it's a keyword which doesn't require the namespace to exist before use. So I wouldn't report it as an unused namespace in your example  My goal was just to find `:require` declarations for namespaces that aren't used, so that can keep code pruned to reasonable sets of stuff we actually seem to be using.

I'm not sure if that fits what you thought could be easily implemented or not, hope it helps.

**Comment by jafingerhut** [comment]
The commit mentioned above looks for all uses of keywords in a namespace, after any `::<namespace-alias>/<keyword-name>` occurrences have been resolved to the full namespace name, and considers a namespace as used if it appears in any keyword reference.

Note that since this is done after macros are expanded, if a keyword appears in a macro expansion, it can cause a namespace to be considered used that way, even if the keyword with that namespace is in a macro definition in a different namespace.  A bit indirect, but the only down-side in this case is that no warning is issued for that namespace being unused.

If you want to try it out to see if it fixes the issue for you before the next Eastwood release, you can check out these instructions for locally installing an unreleased version of Eastwood from source code: https://github.com/jonase/eastwood#for-eastwood-developers
