### ISSUE TITLE
classpath/maven based execution

### ISSUE THREAD

**Issue by stuarthalloway** [jonase/eastwood#223]
Please make classpath/maven based execution (e.g. https://github.com/jonase/eastwood#running-eastwood-in-a-repl) the primary documentation. It is a key value prop of Clojure to run on the giant JVM continent, not the Clojure build tool island.

**Comment by jafingerhut** [comment]
Because it was quick to do so, and perhaps partially satisfies your request, I made two quick changes to Eastwood's README:

+ Made this the first sentence of the 'quick start' section: "Eastwood can be run from within a REPL, regardless of which build tools you may use. See the instructions here.".  It has link to the 'running Eastwood in a REPL' section.

+ Streamlined the entire 'Running Eastwood in a REPL' section.  It now starts with how to do it, and only later describes recommendations for keeping Eastwood and production/dev JVM processes separate, and potential problems you may encounter running Eastwood twice in the same JVM process, which are similar to Clojure code-reloading issues in the same JVM.

Unless the State of Clojure 2016 results are non-representative of Clojure users, Leiningen is 90%+ of the user base, still.

**Comment by stuarthalloway** [comment]
Thanks Andy!  That is indeed helpful.

Large enterprises who are considering adopting Clojure sometimes ask about the availability of linters. Having a good story that works out of the box in the enterprise Java ecosystem (in other words, with maven or sometimes gradle) will help adoption.
