### ISSUE TITLE
Add exclusion rules for defrecord with no fields

### ISSUE THREAD

**Issue by danielcompton** [jonase/eastwood#231]
This code

```
(defrecord MyRecord [])
```

will generate these warnings:

```
== Linting co.deps.time ==
Entering directory `...'
.../time.clj:360:1: suspicious-expression: condp called with 3 args.  (condp pred test-expr expr) always returns expr.  Perhaps there are misplaced parentheses?
.../time.clj:360:1: suspicious-expression: and called with 1 args.  (and x) always returns x.  Perhaps there are misplaced parentheses?
.../time.clj:360:1: suspicious-expression: case called with 2 args.  (case x y) always returns y.  Perhaps there are misplaced parentheses?
.../time.clj:360:1: suspicious-expression: case called with 2 args.  (case x y) always returns y.  Perhaps there are misplaced parentheses?
```

These could be masked with exclusions?

**Comment by jafingerhut** [comment]
Were you using a recent Clojure 1.9.0 alpha or beta when you saw these?  If so, I have seen them as well, and believe I have fixed them.  Eastwood was using some knowledge of Clojure internal representation of defrecords to recognize empty ones with low false positive rate, and Clojure 1.9.0-alpha<something> has a performance improvement for caching record hashing that broke that.  The Eastwood commit with the fix is here: https://github.com/jonase/eastwood/commit/2df53ae8ba8cabb98f4d6f7cafab62345ec1ffb4

If you want to try it out to see if it fixes the issue for you before the next Eastwood release, you can check out these instructions for locally installing an unreleased version of Eastwood from source code: https://github.com/jonase/eastwood#for-eastwood-developers

**Comment by danielcompton** [comment]
> Were you using a recent Clojure 1.9.0 alpha or beta when you saw these?

Yep, I was. I'll take a look at the new build when I get a chance. Thanks!
