### ISSUE TITLE
Support for on-demand disabling of linters

### ISSUE THREAD

**Issue by rymndhng** [jonase/eastwood#282]
Many linters support the ability to disable a rule on a particular line (in clojure's case, a form). There's some ideas on this [page](https://github.com/jonase/eastwood/blob/master/doc/README-clojure-annotations.md).

**Comment by jafingerhut** [comment]
So I have a few lines of experimental code I had written towards implementing an approach where you add comments with an Eastwood-recognized special format to the contents of the comments.  The page linked above probably already says this, but the main motivation for the comment approach, vs. metadata or something else, is that at least right now, I don't think any tools use the contents of comments to affect how they process Clojure code.  Certainly the Clojure compiler does not.

Currently when Eastwood is processing the contents of one file, it goes into a loop where it uses clojure.tools.reader's read function to read one top level form, then it uses clojure.tools.analyzer.jvm to analyze it.

One idea to read Clojure code and preserve something about the content of the comments (or everything about the content of the comments) would be to return some data structure that is different than what `read` returns today.  If you take this approach, then you must either also change the analyze function to expect that different data structure, or convert it to what `read` returns today before passing on the result to the analyze code.

I didn't like that approach.  What I was working towards was to make a modified version of clojure.tools.reader's `read` function that returns exactly what `read` already does today, but in addition, it returns a data structure indicating where all of the comments are (i.e. line numbers and column numbers), the contents of the comments, and the start and end point of the next Clojure form read after that comment.  So if the next form after a comment was a form like `(if foo :then :else)`, spread over 3 lines, the comment would have data indicating the start (line number, column number) of that form, as well as the end (line number, column number).

Now, run analyze exactly as it is today, and run the Eastwood linters exactly as they are today, generating all warning that they do already.

However, before including the warnings in the output or returned data, check their line number and column number, and if they are within the bounds of a comment that disables that kind of warning, as determined by the data structure with info about all comments and the start and end point of the following form, then skip issuing that warning.

This would require a special case for suppressing warnings that Eastwood currently marks as line 1 column 1 of a file, e.g. allow any comments that are at the top level of the file, say just before or just after the initial `ns` form, to be treated as if they included line 1 column 1 in the warnings they should suppress.

It would also require Eastwood code maintaining its own modified version of clojure.tools.reader, which shouldn't be a huge hassle, since that code has only changed with small bug fixes for the last several years.  It would be some work to merge in future tools.reader fixes, though.

**Comment by ezmiller** [comment]
I'm curious about the status of this idea.

**Comment by jafingerhut** [comment]
I have personally done very little with Eastwood development for the past 3 years or so.  Others have done significantly more work on it in that time than I have -- they may answer for themselves on whether they are interested in developing such a feature for Eastwood.

I have not used it, but I believe clj-kondo has a feature like this, and is quite actively developed and enhanced by its author.

**Comment by rymndhng** [comment]
As the originator of this issue, I also primarily use `clj-kondo` these days.
