### ISSUE TITLE
False positive :implicit-dependencies when using clojure.java-time

### ISSUE THREAD

**Issue by emlyn** [jonase/eastwood#307]
The following code:
```clojure
(ns implicit-deps-test.core
  (:require [java-time :as t]))

(t/offset-date-time 2019 1 1)
```
Triggers the following warning:
```
== Linting implicit-deps-test.core ==
src/implicit_deps_test/core.clj:4:2: implicit-dependencies: Var t/offset-date-time refers to namespace java-time.zone that isn't explicitly required.
== Linting done in 3428 ms ==
== Warnings: 1 (not including reflection warnings)  Exceptions thrown: 0
Subprocess failed
```
And many other `java-time` vars also trigger similar warnings. Might be to do with the fact that it uses `potemkin/import-vars`?

**Comment by viesti** [comment]
So we hit this too. This reminds me of the [single-segment-namespace issue](https://groups.google.com/forum/#!topic/clojure/gOffhotk25Y), although it's probably not the offender here. 

This used to pass with 0.2.5 version of eastwood, but fails with 0.3.5, so something has changed.

**Comment by slipset** [comment]
@lynaghk do you have any thoughts on this?

**Comment by viesti** [comment]
Here's a minimal case to reproduce the error.

```
0% cat src/foo/core.clj
(ns foo.core)

(require 'clojure.java.shell)
(refer 'clojure.java.shell :only ['sh])

(defn foo [x]
  (sh "ls"))
0% lein with-profile +eastwood eastwood
== Eastwood 0.3.5 Clojure 1.9.0 JVM 1.8.0_191 ==
Directories scanned for source files:

src test
== Linting foo.core ==
src/foo/core.clj:7:4: implicit-dependencies: Var sh refers to namespace clojure.java.shell that isn't explicitly required.
```

**Comment by slipset** [comment]
That seems like two different error cases though, doesn't it?
The first case (by @emlyn) shows a standard `(:require)` to a ns which uses `potemkin`, whereas the second case uses a "non-standard" `require/refer` (as in not in the `(ns...)` declaration.

**Comment by viesti** [comment]
Yeah, not exactly the same, tried thinking of other cases with similar property. Non-standard require/refer is an odd thing, not something to encourage.

**Comment by viesti** [comment]
Hmm, seems that `:implicit-dependencies` warning cannot be disabled, the case clause in `process-configs` doesn't seem to have a case fort his (probably hard to limit the scope of this linter)

https://github.com/jonase/eastwood/blob/085d36a91f90da95eb8ffa34e405de460a859188/src/eastwood/util.clj#L886-L899

**Comment by slipset** [comment]
A PR to enable disablement of `:implicit-dependencies` would be very welcome.
I can cut a new release tonight.

**Comment by viesti** [comment]
Got distracted, but found my way out via `:exclude-linters [:implicit-dependencies]`, which disables the linter altogether. Maybe a way to disable the linter for particular namespace(s) could help the case with clojure.java-time. Too far in the evening for cooking up a PR though :)

**Comment by slipset** [comment]
Yeah, I thought there was a way out of that, but couldn’t remember it.
I’ve done some trickery wrt disabling linters for certain regexes, as done in the deprecation linter.
That might work here as well.

In general, Eastwood is lacking a general “ignore” thingy.

**Comment by viesti** [comment]
Late cooking, but whipped up something https://github.com/viesti/eastwood/commit/7429d547f8fdb4366d460b079438d0dd2ba39577. While cooking that, started thinking that providing more info for the linter could also work, say 

```clojure
(disable-warning
  {:linter :implicit-dependencies
    :provided-dependencies {'java-time #{'java-time.local}})
```

Then again, didn't really look into what could be done with tools.namespace.

**Comment by lynaghk** [comment]
> @lynaghk do you have any thoughts on this?

## Thoughts on what's happening
The linter relies on tools.namespace to extract all of the namespaces that are explicitly required: https://github.com/jonase/eastwood/blob/3db170013496d3a1598ebfec6a04ef7ade1d622d/src/eastwood/linters/implicit_dependencies.clj#L28
I suspect what's happening is that tools.namespace looks at the form syntactically rather than via evaluation, so it misses whatever potemkin macro magic that the additional loading and referring.

## Thoughts on what *should* happen

Not sure.

The example @viesti brought up (toplevel `require`) is what I'd consider a "true positive" --- the sort of code the linter was designed to warn about.

The case with Potemkin is less clear --- presumably it's doing some macro magic to implicitly require namespaces, so a strict reading is that the linter is working as designed.
I haven't used Potemkin and so I can't speak to how things "feel", but since they opened an issue it probably feels like a surprise/bug to @emlyn.

If one wanted to allow the latter case but not the former case, the linter would probably have to be rewritten to explicitly recognize whatever forms Potemkin generates.
(Since if we just evaluated everything and then checked whether vars were loaded, it wouldn't be possible to tell these cases apart.)

**Comment by viesti** [comment]
Very well stated thoughts, thank you! :)

**Comment by emlyn** [comment]
> I haven't used Potemkin and so I can't speak to how things "feel", but since they opened an issue it probably feels like a surprise/bug to @emlyn.

@lynaghk I haven't used Potemkin either, I just used `java-time` as a dependency and then started getting warnings about my (correct) ns declaration, so it certainly *feels* like a bug, even though I understand now why it happens.

**Comment by torkus** [comment]
Getting bit by `java-time` as well here:

> implicit-dependencies: Var java-time/zoned-date-time refers to namespace java-time.zone that isn't explicitly required.

and then when I include `java-time.zone` in `ns` declaration, I get:

> unused-namespaces: Namespace java-time.zone is never used in wowman.utils

thanks for your work on `eastwood` though, I imagine code linting is a wonderfully complex problem to tackle :)

**Comment by emlyn** [comment]
I'm also seeing this when I use [ubergraph](https://github.com/Engelberg/ubergraph) (presumably because it also uses potemkin [here](https://github.com/Engelberg/ubergraph/blob/9cc999972bc0c541beab0a0f27e607dd022d7962/src/ubergraph/core.clj#L11)).

**Comment by vemv** [comment]
This happens because in a potemkinized var, its `:ns` metadata will point to its "source" namespace, instead of to the namespace that is doing the `import-vars`.

That dissonance confuses this LOC:

https://github.com/jonase/eastwood/blob/19c0f86e16342c00f4521c8a689c3892bddb7c84/src/eastwood/linters/implicit_dependencies.clj#L8

...I believe the fix could be simple. e.g. from this sample session:

```clj
user> (symbol #'pandect/sha512)
pandect.core/sha512
user> (-> #'pandect/sha512 meta :ns)
#namespace[pandect.algo.sha512] ;; dissonance between pandect.core/sha512 and pandect.algo.sha512
```

we can observe that `symbol` is more reliable than metadata inspection. So the mentioned LOC could use that method.

**Comment by vemv** [comment]
I can confirm that worked :)

There's one last pain point (unrelated to Potemkin, but related to false positives). This LOC: https://github.com/jonase/eastwood/blob/19c0f86e16342c00f4521c8a689c3892bddb7c84/src/eastwood/linters/implicit_dependencies.clj#L28 performs ns-parsing which isn't as comprehensive as inspecting `(ns-interns *ns*)` or such.

The difference is that one can always add `require`s by hand after the ns form - a nuance which `deps-from-ns-decl` doesn't cover.

I can't PR these atm ⚖️ - anyone would want to give them a shot?
