### ISSUE TITLE
Exception on Custom macro execution

### ISSUE THREAD

**Issue by avikoren** [jonase/eastwood#347]
I have the following custom macro in our code
`(uql (coll owner fields [dmv/address/zip]))`
the `uql` is the macro. Eastwood throw an exception:
```
:cause "----/afw/querycycle_test.clj [line 358, col 71] Invalid symbol: dmv/address/zip."
 :data {:type :reader-exception, :ex-kind :reader-error, :file "----/afw/querycycle_test.clj", :line 358, :col 71}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "----/afw/querycycle_test.clj [line 358, col 71] Invalid symbol: dmv/address/zip."
   :data {:type :reader-exception, :ex-kind :reader-error, :file "----/afw/querycycle_test.clj", :line 358, :col 71}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4739]}]
```

**Comment by vemv** [comment]
FWIW `dmv/address/zip` _is_ an invalid symbol, since it contains two slashes. There can be one at most, denoting a namespace

It is known that there are keywords/symbols that sometimes can be passed around even if they aren't valid: https://clojure.org/guides/faq#unreadable_keywords

Personally I'd be wary of authoring a macro that leveraged this grey zone much; also wouldn't be surprised if various tools break.

**Comment by avikoren** [comment]
The symbol `dmv/address/zip` is not a namespace, but a symbol that is parsed by a macro. This specific symbol denotes a path for a value in an nested data document.
I understand that the regular use of symbol is not as the way is used here. but the idea of LISP based language is to use data as code, isn't it? This options enable us to have DSL in place for the readability of the code and ease of use of the underline library.
What do you suggest me to do ?

**Comment by jafingerhut** [comment]
As far as the root cause of this issue goes, Eastwood uses the tools.reader library to read Clojure code: https://github.com/clojure/tools.reader

As the REPL session below shows, the tools.reader library is more strict than Clojure's built-in reader for input like `dvm/address/zip`.  tools.reader is an independent implementation that follows the behavior of Clojure's built in reader in most ways, but not all.  In this case, the difference is probably because the Clojure implementation is more permissive in what it supports than the Clojure official documentation (or the Clojure official documentation is perhaps not so precise in its language that there is room for different interpretations, which has happened before for other questions of what is supported vs. what is not).

```
$ clojure -Sdeps '{:deps {org.clojure/tools.reader {:mvn/version "1.3.4"}}}'
Clojure 1.10.1
user=> (clojure.core/read-string "dvm/address/zip")
dvm/address/zip
user=> (clojure.edn/read-string "dvm/address/zip")
dvm/address/zip
user=> (require '[clojure.tools.reader :as tr])
nil
user=> (tr/read-string "dvm/address/zip")
Execution error (ExceptionInfo) at clojure.tools.reader.impl.errors/throw-ex (errors.clj:34).
Invalid symbol: dvm/address/zip.
```

I have never tried changing Eastwood to use Clojure's built-in reader to see whether it works that way, or not.

**Comment by vemv** [comment]
> but the idea of LISP based language is to use data as code, isn't it?

I guess so, but at the same time an invalid token isn't a great piece of data :) a vanilla string is more data-y than a symbol. Symbols relate more to "code" (something a programmer would author), while strings relate more to "data" (something an end user would author or care about)

> This options enable us to have DSL in place for the readability of the code and ease of use of the underline library.

In case it helps, DSLs are quite often frowned upon in the Clojure world; or at least more than in other lisps or a cousin lang like Ruby. You can find traces of this thinking in various talks and articles.

> What do you suggest me to do?

It's common wisdom among Clojurists to prefer functions over macros, and data over code.

Hope it helps!

**Comment by avikoren** [comment]
Thanks vemv, I appreciate your answer.
just to clarification, the use of DSL here with symbols is intended to be uses by developer. It is just like an advanced way to work with APIs (but on specific DSL syntax) of the underline layer/component.
Probably, we need to rethink about the syntax of this language to be less "problematic"...
It will be nice if you can send me a reference to one of these articles you mentioned. (only if it is with-in reach)
