### ISSUE TITLE
Test expression is always true/false when setting `:min-count` for `spec/every` family of functions 

### ISSUE THREAD

**Issue by clov0** [jonase/eastwood#435]
Eastwood keeps getting me warnings for these spec lines :
```
(spec/map-of
    (spec/spec string?
               :gen (fn [] (gen/fmap
                             #(apply str %)
                             (gen/vector
                               gen/char-alpha
                               5 20))))
    (spec/coll-of
      (spec/tuple ::i-commons/source ::sub-type)
      :into #{}
      :min-count 2
      :gen-max 7)
    :min-count 2
    :gen-max   8)
```
the error is :

```
== Linting hermes.van-buren.core.event.rlc.model ==
src/hermes/van_buren/core/event/rlc/model.clj:201:3: constant-test: Test expression is always logical true or always logical false: 2 in form (if or__5533__auto__ or__5533__auto__ (clojure.core/or 0)).
src/hermes/van_buren/core/event/rlc/model.clj:201:3: constant-test: Test expression is always logical true or always logical false: nil in form (if nil (clojure.core/inc nil) 2).
src/hermes/van_buren/core/event/rlc/model.clj:201:3: constant-test: Test expression is always logical true or always logical false: nil in form (if or__5533__auto__ or__5533__auto__ (clojure.core/or java.lang.Integer/MAX_VALUE)).

```
Removing the :min-count option from the `spec/map-of` and the likes fixes the warning.

**Comment by vemv** [comment]
Hi! Thanks for the report.

Are you using Eastwood latest?

After confirming that, are you familiar with the notion of "config files"? Here are the ones targeting clojure.spec: https://github.com/jonase/eastwood/blob/5a55eff81aff75dbca94adfb7f18e956e52fcf55/resource/eastwood/config/clojure.clj#L42-L57

It might be that they need to be updated in face of clojure.spec changes.

Feel free to play with adding your own `:config-files [,,,]`:

https://github.com/jonase/eastwood/blob/5a55eff81aff75dbca94adfb7f18e956e52fcf55/README.md?plain=1#L409-L413

If you find something that works, feel free to share. Otherwise I'll tackle this asap but not urgently.

Cheers - V

**Comment by vemv** [comment]
1.2.4 is being released this morning!
